src/MyNunitWeb/MyNunitWeb/Models/AssemblyModel.cs
namespace MyNunitWeb.Models;

using System.ComponentModel.DataAnnotations;

/// <summary>
/// Model for assembly with tests
/// </summary>
public class AssemblyModel
{
    [Key]
    public int Id { get; init; }
    public string Name { get; init; }
    public List<TestModel> Tests { get; set; }
}

src/MyNunitWeb/MyNunitWeb/Models/TestModel.cs
namespace MyNunitWeb.Models;

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

/// <summary>
/// Model for test
/// </summary>
public class TestModel
{
    [Key]
    public int Id { get; set; }
    public string Name { get; init; }
    public string Result { get; init; }
    public string IgnoreReason { get; init; }
    public long ExecutionTime { get; init; }

    [ForeignKey("AssemblyModel.Id")]
    public int AssemblyModelId { get; init; }
}

src/MyNunitWeb/MyNunitWeb/Pages/Error.cshtml.cs
namespace MyNunitWeb.Pages;

using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
[IgnoreAntiforgeryToken]
public class ErrorModel : PageModel
{
    public string RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

    private readonly ILogger<ErrorModel> _logger;

    public ErrorModel(ILogger<ErrorModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {
        RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
    }
}

src/MyNunitWeb/MyNunitWeb/Pages/History.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MyNUnit;
namespace MyNunitWeb.Pages;

using MyNunitWeb.Data;
using MyNunitWeb.Models;

public class HistoryModel : PageModel
{
    public List<TestModel> TestResults { get; set; }
    public List<AssemblyModel> TestsAssemblies { get; set; }

    private readonly ApplicationDbContext _dbContext;

    public HistoryModel(ApplicationDbContext dbContext)
    {
        _dbContext = dbContext;
    }

    public void OnGet()
    {
        TestResults = _dbContext.TestResults.ToList();
        TestsAssemblies = _dbContext.TestAssemblies.ToList();

        foreach (var assembly in TestsAssemblies)
        {
            assembly.Tests = TestResults.Where(test => test.AssemblyModelId == assembly.Id).ToList();
        }
    }

    public int GetAmountOfTestsOfResult(AssemblyModel assembly, TestResult testResult)
    {
        return assembly.Tests.Where(test => test.Result.Equals(testResult.ToString())).Count();
    }
}

src/MyNunitWeb/MyNunitWeb/Pages/Index.cshtml.cs
namespace MyNunitWeb.Pages;

using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MyNunitWeb.Models;
using MyNUnit;
using System.Collections.Concurrent;
using MyNunitWeb.Data;

public class IndexModel : PageModel
{
    private readonly IWebHostEnvironment _environment;
    private readonly ApplicationDbContext _dbContext;

    [BindProperty]
    public List<string> LoadedFilePaths { get; set; } = new List<string>();

    public List<AssemblyModel> Assemblies { get; set; } = new List<AssemblyModel>();

    public IndexModel(IWebHostEnvironment environment, ApplicationDbContext dbContext)
    {
        _environment = environment;
        _dbContext = dbContext;
    }

    public void OnGet()
    {
    }

    public void OnPost(IFormFile[] dlls)
    {
        if (dlls != null && dlls.Length > 0)
        {
            foreach (IFormFile dll in dlls)
            {
                var path = Path.Combine(_environment.WebRootPath, "dlls", dll.FileName);
                using var stream = new FileStream(path, FileMode.Create);
                dll.CopyToAsync(stream);
                LoadedFilePaths.Add(path);
            }
        }
        return;
    }

    public void OnPostStartTesting()
    {
        ProcessTests();
        SaveResultsToDb();
    }

    private void ProcessTests()
    {
        var testAndAssemblies = RunTestsWithMyNuint(LoadedFilePaths);
        foreach (var assembly in testAndAssemblies)
        {
            var tests = new List<TestModel>();
            foreach (var test in assembly.Value.ToList())
            {
                tests.Add
                (
                    new TestModel
                    {
                        Name = test.TestName,
                        IgnoreReason = !string.IsNullOrEmpty(test.ErrorMessage) ? test.ErrorMessage : test.IgnoreReason,
                        ExecutionTime = test.ExecutionTime,
                        Result = test.Result.ToString()
                    }
                );
            }
            Assemblies.Add(new AssemblyModel { Name = assembly.Key, Tests = tests });
        }
    }

    private Dictionary<string, ConcurrentBag<TestState>> RunTestsWithMyNuint(List<string> testPaths)
    {
        var myNUnit = new MyNUnit();
        return myNUnit.GetTestResultsAndAssembliesByPath(testPaths);
    }

    private void SaveResultsToDb()
    {
        _dbContext.TestAssemblies.AddRange(Assemblies);
        foreach (var assembly in Assemblies)
        {
            _dbContext.TestResults.AddRange(assembly.Tests);
        }
        _dbContext.SaveChanges();
    }
}

src/MyNunitWeb/MyNunitWeb/Pages/History.cshtml
@page
@model MyNunitWeb.Pages.HistoryModel
@{
    <div class="container p-3">
            <div class="row pt-4">
                <div class="col-6">
                    <h2>Tests run history</h2>  
                </div>
            </div>

        <div class="mt-4">
            @foreach (var assembly in Model.TestsAssemblies)
            {
                <div class="mt-5">
                    <label class><strong>@assembly.Name</strong>
                    total tests: @assembly.Tests.Count, 
                    success: @Model.GetAmountOfTestsOfResult(assembly, MyNUnit.TestResult.Success),
                    failed: @Model.GetAmountOfTestsOfResult(assembly, MyNUnit.TestResult.Failed),
                    ignored: @Model.GetAmountOfTestsOfResult(assembly, MyNUnit.TestResult.Ignored)
                    </label>
                    <br>
                    <table class="table table-bordered table-striped" style="width:100%">
                        <thead>
                            <tr>
                                <th>
                                    Test name
                                </th>
                                <th>
                                    Test status
                                </th>
                                <th>
                                    Test run information
                                </th>
                                <th>
                                    Execution time (ms)
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var test in assembly.Tests)
                            {
                                <tr class=@(Helper.GetTableRowType(test.Result))>
                                    <td width="10%">@test.Name</td>
                                    <td width="30%">@test.Result</td>
                                    <td width="30%">@test.IgnoreReason</td>
                                    <td width="10%">@test.ExecutionTime.ToString()</td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            }
        </div>
    </div>
}

src/MyNunitWeb/MyNunitWeb/Pages/Index.cshtml
@page
@using MyNUnit
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">

    <div class="container" p-3>
        <h2>Welcome</h2>
        <br/>
        <div>
            <h6>
                MyNunitWeb is a simple tool to run tests. To run your tests upload dll files, containing testing classes and unit tests
                and press "Run tests" button. You can see your tests launch history at the <a asp-page="/History">History</a> page.
            </h6>

        </div>
    </div>

    <div class="container" p-3>
        <div class="row pt-4 align-content-center">

            <div class="container">
                <form method="post" asp-page="Index" enctype="multipart/form-data">

                    <div class="row align-items-center">
                        <div class="col-10">
                            <input class="form-control" name="dlls" type="file" id="formFile">
                        </div>
                        <div class="col-1">
                            <input type="submit" value="Upload" class="btn btn-outline-secondary" />
                        </div>
                        <div class="col-1"></div>
                    </div>

                    @if (Model.LoadedFilePaths != null)
                    {
                        @for (int i = 0; i < Model.LoadedFilePaths.Count; i++)
                        {
                            <input hidden="hidden" asp-for="@Model.LoadedFilePaths[i]" value="@Model.LoadedFilePaths[i]" class="form-control" />
                        }
                    }

                    <div class="m-4 align-content-center">
                        <label> <strong>Selected files:</strong> </label>
                        @for (int i = 0; i < Model.LoadedFilePaths.Count; i++)
                        {
                            @if (i == Model.LoadedFilePaths.Count - 1) {
                                <label>
                                    @Model.LoadedFilePaths[i].
                                </label>
                            }
                            else {
                                <label>
                                    @Model.LoadedFilePaths[i]; 
                                </label>
                            }
                        }
                    </div>
                    <div class="m-4 align-content-center">
                        <button type="submit" asp-page-handler="StartTesting" class="btn btn-secondary">Run tests</button>
                    </div>
                </form>
            </div>

            <div>
                @foreach (var assembly in Model.Assemblies)
                {
                    <label class="text-lg-start"><strong>@assembly.Name</strong></label>
                    <br/>
                    <table class="table table-bordered table-striped" style="width:100%">
                        <thead>
                            <tr>
                                <th>
                                    Test name
                                </th>
                                <th>
                                    Test status
                                </th>
                                <th>
                                    Test run information
                                </th>
                                <th>
                                    Execution time (ms)
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var test in assembly.Tests)
                            {
                                <tr class = @(Helper.GetTableRowType(test.Result)) >
                                <td width="10%">@test.Name</td>
                                <td width="30%">@test.Result</td>
                                    <td width="30%">@test.IgnoreReason</td>
                                <td width="10%">@test.ExecutionTime.ToString()</td>
                                </tr>
                            }
                        </tbody>
                    </table>
                }
            </div>
        </div>
    </div>
</div>

src/MyNunitWeb/MyNunitWeb/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MyNUnitWeb</title>
    <link rel="stylesheet" href="~/css/bootswatch_cosmo.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MyNunitWeb.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">MyNunitWeb</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/History">History</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - MyNunitWeb
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>